services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:${API_PORT:-9001}

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/src:/app/src
      - api_secrets:/data/secrets
    command: npm run start:dev

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - ./worker/src:/app/src
    environment:
      SCANNER_MOCK_MODE: "true"
